[package]
name = "gi_rust"
version = "0.1.0"
authors = ["LangPham <langpham@theta.vn>"]
edition = "2018"

[lib]
name = "gi_rust"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
image = "0.24.3"
rustler = "0.25.0"
